<a href="https://colab.research.google.com/github/WalterLoor1/inteligenciaArtificial/blob/main/01-07-2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a=np.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[0], a[1])
print(a[0:2])
print(a[1:])

a[1]=888
print(a)


(3,)
<class 'numpy.ndarray'>
[11 22 33]
11 22
[11 22]
[22 33]
[ 11 888  33]


In [2]:
b=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])
aux=b[1:,1:].copy()
print(aux.shape)
print(aux)

print('ANTES....')
print(b)
print(aux)

aux[1,1]=1000

print('DESPUES...')
print(b)
print(aux)

(3, 3)
<class 'numpy.ndarray'>
[[11 22 33]
 [44 55 66]
 [77 88 99]]
55
(2, 2)
[[55 66]
 [88 99]]
ANTES....
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[55 66]
 [88 99]]
DESPUES...
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[  55   66]
 [  88 1000]]


In [3]:
c=np.zeros((4,4))
print(c)
print(c.shape)

d=np.full((4,4),9)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [5]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
g=np.random.random((5,5))
print(g)

[[0.20686026 0.98739074 0.45603979 0.50498618 0.27503276]
 [0.8403465  0.06647485 0.90501682 0.09235277 0.34350037]
 [0.90806807 0.10442474 0.14724265 0.81950163 0.54883183]
 [0.08510072 0.91704375 0.80838014 0.73721385 0.52471133]
 [0.42877074 0.36917284 0.41992999 0.89374162 0.04357424]]


In [7]:
tmp1=np.random.randint(1,21, size=(4,4))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)

print(rows)
print(cols)

[[10  3 18  2]
 [ 2  8 20  1]
 [ 9  5  4 11]
 [ 2  3 15  4]]
[0 1 2 0]
[0 1 2 3]


In [8]:
tmp1[rows, cols]=100
print(tmp1)

[[100   3  18 100]
 [  2 100  20   1]
 [  9   5 100  11]
 [  2   3  15   4]]


In [9]:
tmp2=np.random.randint(20,50, size=(6,6))
print(tmp2)

[[33 20 25 25 40 47]
 [39 33 43 23 33 29]
 [24 44 36 20 42 27]
 [33 27 39 38 26 39]
 [43 42 23 47 26 36]
 [39 23 45 43 34 32]]


In [10]:
mask = tmp2 > 45
print(mask)
elemay = tmp2[mask]

print("Elementos mayores a 45:")
print(elemay)


[[False False False False False  True]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]
 [False False False False False False]]
Elementos mayores a 45:
[47 47]


In [11]:
tmp3=np.random.randint(1,100, size=(10,10))
print(tmp3)

[[75 44 48  1  8 95 50 32 47  3]
 [13 77 39 37  7 91 63 34 48 91]
 [95 34 12 66 73 89 11 91 56 32]
 [54 55 13 23 47 23  7 96 53 29]
 [81 46 18 94 31 31 48 63 32 37]
 [66 27 67 76 16 79  6 98 84 36]
 [74 13 17 69 59 70 47 71 49 42]
 [13 64 81 77 37 28 16 21 20 41]
 [42 84 53 40 47 64 19 31 87 59]
 [56 94 60 66 28 24 51 21 82 76]]


In [12]:
mask2 = ((tmp3%2)==0)
# print(mask2)
elepar = tmp3[mask2]

print("Elementos pares:")
print(elepar)

Elementos pares:
[44 48  8 50 32 34 48 34 12 66 56 32 54 96 46 18 94 48 32 66 76 16  6 98
 84 36 74 70 42 64 28 16 20 42 84 40 64 56 94 60 66 28 24 82 76]


In [13]:
tmp4=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp4.dtype)
print(tmp4)

float64
[1. 2. 3. 4. 5.]


In [14]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x)
print(y)
print('SUMA')
print(np.add(x,y))
print('RESTA')
print(np.subtract(x,y))
print('MULTIPLICACION')
print(np.multiply(x,y))
print('DIVISION')
print(np.divide(x,y))
print('RAIZ')
print(np.sqrt(x))
print('POTENCIA')
print(np.power(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
SUMA
[[ 6  8]
 [10 12]]
RESTA
[[-4 -4]
 [-4 -4]]
MULTIPLICACION
[[ 5 12]
 [21 32]]
DIVISION
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
RAIZ
[[1.         1.41421356]
 [1.73205081 2.        ]]
POTENCIA
[[    1    64]
 [ 2187 65536]]


In [15]:
tmp5=np.random.randint(1,10, size=(2,5))
print(tmp5)
aux=tmp5.mean()
print(aux)

[[5 9 7 1 7]
 [7 7 2 8 7]]
6.0


In [16]:
print(tmp5.mean(axis=1))
print(tmp5.mean(axis=0))

[5.8 6.2]
[6.  8.  4.5 4.5 7. ]
