<a href="https://colab.research.google.com/github/WalterLoor1/inteligenciaArtificial/blob/main/Introducci%C3%B3n%20a%20Python%20y%20NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                              Universidad Laica  
                                 Eloy Alfaro

                    Nombre: Walther Andres Loor Zambrano  

              Tema: Ejercicios de introducción a Python y NumPy

In [1]:
# Importa la librería numpy y la asigna al alias np
import numpy as np

# Imprime la versión actual de la librería numpy que se está utilizando
print(np.__version__)


1.25.2


In [2]:
import numpy as np

# Crear un arreglo unidimensional de números del 0 al 9
array_1d = np.arange(10)

# Imprimir el arreglo
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np

# Crear un vector aleatorio de tamaño 10
random_vector = np.random.rand(10)

# Imprimir el vector original
print("Vector original:", random_vector)

# Encontrar el índice del valor máximo
max_index = np.argmax(random_vector)

# Reemplazar el valor máximo por 0
random_vector[max_index] = 0

# Imprimir el vector modificado
print("Vector modificado:", random_vector)

Vector original: [0.30986224 0.86630766 0.65891648 0.70219795 0.54666759 0.52861003
 0.32427322 0.20248654 0.77593378 0.85813953]
Vector modificado: [0.30986224 0.         0.65891648 0.70219795 0.54666759 0.52861003
 0.32427322 0.20248654 0.77593378 0.85813953]


In [4]:
import numpy as np

# Definir el arreglo
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimir el número 8 del arreglo
print(arr[1, 2])


8


In [5]:
import numpy as np

# Definir el arreglo
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los números [3, 4, 5] del arreglo
print(arr[2:5])


[3 4 5]


In [6]:
import numpy as np

# Definir el arreglo
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los últimos 4 números del arreglo
print(arr[-4:])


[4 5 6 7]


In [7]:
import numpy as np

# Crear un arreglo de 3x3 con todos los valores True
array_true = np.full((3, 3), True)

# Imprimir el arreglo
print(array_true)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
import numpy as np

# Definir el arreglo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extraer todos los números impares del arreglo
odd_numbers = arr[arr % 2 != 0]

# Imprimir los números impares
print(odd_numbers)


[1 3 5 7 9]


In [9]:
import numpy as np

# Crear un vector con valores que van de 10 a 49
vector = np.arange(10, 50)

# Imprimir el vector
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
import numpy as np

# Crear un vector de ejemplo
vector = np.arange(10, 50)

# Invertir el vector
reversed_vector = vector[::-1]

# Imprimir el vector invertido
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
import numpy as np

# Crear un arreglo de 10x10 con valores enteros aleatorios entre 0 y 100
array_10x10 = np.random.randint(0, 100, size=(10, 10))

# Encontrar el valor mínimo en el arreglo
min_value = np.min(array_10x10)

# Encontrar el valor máximo en el arreglo
max_value = np.max(array_10x10)

# Imprimir el arreglo, el valor mínimo y el valor máximo
print("Arreglo 10x10 con valores aleatorios:")
print(array_10x10)
print("Valor mínimo:", min_value)
print("Valor máximo:", max_value)


Arreglo 10x10 con valores aleatorios:
[[83 13 99 60 66 53 79  5 28 71]
 [68 91 34 57 79 54 58 60  1 95]
 [37 27 54 94 54 12 58 26 37 60]
 [57 52 99 45 59 88 44 26 77 19]
 [21 74 28 14 91 51 98 99 60 41]
 [96  9 15  4 36 47 47 51 89 21]
 [77 54 53 16 20 83 99 41 83 36]
 [50 10  0 73  6 51 95 61 21 71]
 [25 13 91 66 99 41 29 67 63 86]
 [51 11 10 68  5 91 59 44  4  4]]
Valor mínimo: 0
Valor máximo: 99


In [12]:
import numpy as np

# Crear un arreglo de 3x3x3 con valores aleatorios
array_3x3x3 = np.random.random((3, 3, 3))

# Imprimir el arreglo
print(array_3x3x3)


[[[0.34163401 0.96415989 0.17441059]
  [0.44721724 0.66440232 0.14179766]
  [0.98144607 0.55400375 0.33456653]]

 [[0.89407532 0.41085423 0.37936069]
  [0.91216429 0.85970186 0.15120543]
  [0.1305214  0.76422592 0.65215068]]

 [[0.48141777 0.78077687 0.09009125]
  [0.81953589 0.40998507 0.15940957]
  [0.78481131 0.8038215  0.82372629]]]


In [13]:
import numpy as np

# Definir el arreglo
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Reemplazar todos los números impares con -1
arr[arr % 2 != 0] = -1

# Imprimir el arreglo modificado
print(arr)


[-1  2 -1  4 -1  6 -1  8 -1 10]


In [14]:
import numpy as np

# Crear un arreglo de tipo float
float_array = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)

# Imprimir el arreglo y su tipo de dato
print(float_array)
print("Tipo de dato del arreglo:", float_array.dtype)


[1. 2. 3. 4. 5.]
Tipo de dato del arreglo: float64


In [15]:
import numpy as np

# Crear un arreglo unidimensional
array_1d = np.arange(10)  # Ejemplo de un arreglo con 10 elementos

# Convertir el arreglo unidimensional a un arreglo bidimensional con 2 filas
array_2d = array_1d.reshape(2, -1)

# Imprimir el arreglo bidimensional
print(array_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
import numpy as np

# Crear dos arreglos aleatorios
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Encontrar los valores comunes entre los dos arreglos
common_values = np.intersect1d(Z1, Z2)

# Imprimir los arreglos y los valores comunes
print("Arreglo Z1:", Z1)
print("Arreglo Z2:", Z2)
print("Valores comunes:", common_values)


Arreglo Z1: [8 2 6 6 5 6 7 5 3 8]
Arreglo Z2: [7 6 1 6 0 8 6 4 5 9]
Valores comunes: [5 6 7 8]


In [17]:
import numpy as np

# Crear dos arreglos aleatorios
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Verificar si los arreglos son iguales
are_equal = np.array_equal(A, B)

# Imprimir los arreglos y el resultado de la comparación
print("Arreglo A:", A)
print("Arreglo B:", B)
print("¿Son iguales?", are_equal)


Arreglo A: [0 0 0 0 1]
Arreglo B: [0 0 1 0 0]
¿Son iguales? False


In [18]:
import numpy as np

# Definir los arreglos a y b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apilar los arreglos verticalmente
stacked_array = np.vstack((a, b))

# Imprimir el arreglo apilado
print(stacked_array)


[[1 2 3]
 [4 5 6]]


In [19]:
import numpy as np

# Definir los arreglos a y b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Apilar los arreglos horizontalmente
stacked_array = np.hstack((a, b))

# Imprimir el arreglo apilado
print(stacked_array)


[1 2 3 4 5 6]


In [20]:
import numpy as np

# Crear el arreglo tmp
tmp = np.arange(15)

# Obtener todos los elementos entre 5 y 10
items_between_5_and_10 = tmp[(tmp >= 5) & (tmp <= 10)]

# Imprimir los elementos obtenidos
print(items_between_5_and_10)


[ 5  6  7  8  9 10]


In [21]:
import numpy as np

# Definir la función escalar
def maxx(x, y):
    """Obtener el máximo de dos elementos"""
    if x >= y:
        return x
    else:
        return y

# Vectorizar la función para que funcione con arreglos numpy
pair_max = np.vectorize(maxx)

# Crear arreglos de ejemplo
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Aplicar la función vectorizada a los arreglos
result = pair_max(a, b)

# Imprimir el resultado
print(result)


[6 7 9 8 9 7 5]


In [22]:
import numpy as np

# Crear el arreglo arr
arr = np.arange(9).reshape(3, 3)
print("Arreglo original:")
print(arr)

# Intercambiar las columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

# Imprimir el arreglo modificado
print("Arreglo después de intercambiar las columnas 1 y 2:")
print(arr)


Arreglo original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Arreglo después de intercambiar las columnas 1 y 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [23]:
import numpy as np

# Crear un arreglo 2D de forma 5x3 con números decimales aleatorios entre 5 y 10
array_2d = np.random.uniform(5, 10, size=(5, 3))

# Imprimir el arreglo
print(array_2d)


[[5.20347092 6.5159115  6.52333338]
 [6.74116554 5.20452146 5.60248174]
 [5.32612791 7.5835811  6.67199077]
 [5.85545874 9.47696171 6.51621722]
 [5.83428659 6.70021197 5.17135277]]
